spring.application.name=leave-management-backend

# Use Railway ENV variables
spring.datasource.url=mysql://root:UFRMYmIuxWmxvNSqFJGZJPUqRJmVWTLZ@metro.proxy.rlwy.net:40382/railway
spring.datasource.username=root
spring.datasource.password=UFRMYmIuxWmxvNSqFJGZJPUqRJmVWTLZ

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Mail (keep as is)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=patelmann576@gmail.com
spring.mail.password=finemgityocaaeze
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# JWT
jwt.secret=${JWT_SECRET}