spring.application.name=leave-management-backend
spring.datasource.url=jdbc:mysql://localhost:3306/leave_management
spring.datasource.username=root
spring.datasource.password=Shivay@1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=patelmann576@gmail.com
spring.mail.password=finemgityocaaeze

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect